# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ef43661159b4d3e58fc9ae29cf76d6258641ec1deae89fb4153ad7921d1d4f0d946568b7343a69131cf96c494c1e749a4a3760cffdd743fdb62b5ecb06fe07a

test:
  secret_key_base: 52e8221a8219425dd25b86e328b62b479b49a7530fca34cf76733d61fdbf3d2c7702a3032f0a17317561e98ce6c4d4aa07ed9d7b02c8283c72523972dd3a4aa1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
